In [737]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns 

In [738]:
train = pd.read_csv('/Users/mariojosetuppia/Desktop/Hackaton/train.csv')

In [739]:
test = pd.read_csv ('/Users/mariojosetuppia/Desktop/Hackaton/test_x.csv')

In [740]:
train

Unnamed: 0  Hour  Minutes  Sensor_alpha  Sensor_beta  Sensor_gamma  \
0              0    22       26    119.910995   242.838324   -316.819222   
1              1    10       16    -90.790536  -269.470767   -182.581844   
2              2    21       42    -20.028003  -147.070212     50.280872   
3              3    21       17    -21.258567     0.467070    -86.164153   
4              4    18       16    -58.154501   -13.051195   -156.501167   
...          ...   ...      ...           ...          ...           ...   
6996        6996    21        0      6.576106   301.050638    146.682819   
6997        6997    18       57     -6.169382  -317.652257   -161.644320   
6998        6998    22       47     -7.289684  -406.732525   -212.097250   
6999        6999    18       14    -92.317105  -191.555040     88.371271   
7000        7000    21       31    -72.083585   -11.434977    -52.961743   

      Sensor_alpha_plus  Sensor_beta_plus  Sensor_gamma_plus  Insect  
0            250.195048        -53.547777        -112.049983       2  
1             95.394941         37.291944          48.525180       0  
2            -90.750386        -50.476556          85.399009       1  
3            -21.813529       -209.256006          16.291882       0  
4             48.392938       -110.008860         -10.285138       2  
...                 ...               ...                ...     ...  
6996        -209.480741       -129.776336         -51.226256       1  
6997         248.055724       -112.626344          99.463913       0  
6998         248.745127        116.893077          32.806150       0  
6999          38.728565        -39.050466          20.356711       0  
7000         -72.696385        145.299227        -143.856243       1  

[7001 rows x 10 columns]

### Descripción de los Datos 

In [741]:
train.describe()

Unnamed: 0         Hour      Minutes  Sensor_alpha  Sensor_beta  \
count  7001.00000  7001.000000  7001.000000   7001.000000  7001.000000   
mean   3500.00000    19.598914    29.405942      0.477171   -29.974117   
std    2021.15895     3.507008    17.375830     99.294856   133.095125   
min       0.00000     1.000000     0.000000   -404.898823  -656.272666   
25%    1750.00000    19.000000    14.000000    -68.573905  -116.060383   
50%    3500.00000    21.000000    29.000000     -0.287447   -36.171567   
75%    5250.00000    21.000000    44.000000     66.480795    56.637778   
max    7000.00000    23.000000    59.000000    351.256221   518.395878   

       Sensor_gamma  Sensor_alpha_plus  Sensor_beta_plus  Sensor_gamma_plus  \
count   7001.000000        7001.000000       7001.000000        7001.000000   
mean      -5.624690           7.188060         -0.757901          -0.554533   
std      115.871391         122.327980        100.039477         100.535951   
min     -448.478039        -437.205393       -387.567443        -374.961689   
25%      -83.508747         -79.496687        -68.061596         -69.652647   
50%       -1.217606          -1.133567         -0.444124           0.027128   
75%       76.870277          93.285286         66.181909          67.838524   
max      378.349287         462.556319        345.279240         363.682391   

            Insect  
count  7001.000000  
mean      0.595772  
std       0.661604  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       1.000000  
max       2.000000

In [742]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7001 entries, 0 to 7000
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Unnamed: 0         7001 non-null   int64  
 1   Hour               7001 non-null   int64  
 2   Minutes            7001 non-null   int64  
 3   Sensor_alpha       7001 non-null   float64
 4   Sensor_beta        7001 non-null   float64
 5   Sensor_gamma       7001 non-null   float64
 6   Sensor_alpha_plus  7001 non-null   float64
 7   Sensor_beta_plus   7001 non-null   float64
 8   Sensor_gamma_plus  7001 non-null   float64
 9   Insect             7001 non-null   int64  
dtypes: float64(6), int64(4)
memory usage: 547.1 KB


In [743]:
train.columns

Index(['Unnamed: 0', 'Hour', 'Minutes', 'Sensor_alpha', 'Sensor_beta',
       'Sensor_gamma', 'Sensor_alpha_plus', 'Sensor_beta_plus',
       'Sensor_gamma_plus', 'Insect'],
      dtype='object')

In [744]:
test =test.drop([0])

In [745]:
test

Unnamed: 0  Hour  Minutes  Sensor_alpha  Sensor_beta  Sensor_gamma  \
1           7001    21        3   -193.619980    40.137081     85.419244   
2           7002    22       31     42.578382   -51.613402    125.055611   
3           7003    21       25    -64.150951   287.306752    -70.965473   
4           7004    18       11    193.750787   -61.989533   -110.347066   
5           7005    21        5    200.151155   -69.828082   -103.909275   
...          ...   ...      ...           ...          ...           ...   
2995        9995     3       26   -101.913083    87.337077     77.193476   
2996        9996    21        6     52.424913   -37.107249    120.373905   
2997        9997    21        0   -103.295133    34.736979   -195.018118   
2998        9998    20       13    170.027159   -73.100306   -117.330651   
2999        9999    19       17   -173.839238    66.386097   -141.968498   

      Sensor_alpha_plus  Sensor_beta_plus  Sensor_gamma_plus  
1            -26.266801       -125.391237          80.904973  
2            182.136746         -9.726951        -114.913402  
3             13.789738         38.187260         137.761691  
4            -16.864786        148.541916         232.424616  
5             58.307127          6.339606         -58.217237  
...                 ...               ...                ...  
2995         -79.694034         13.273965         143.004786  
2996         208.090551       -135.567057         -53.867634  
2997        -164.294768        -26.993064           6.063715  
2998          11.353824         -3.366007        -140.113661  
2999         197.558808        -44.847981         142.537872  

[2999 rows x 9 columns]

In [746]:
train.isnull().sum()

Unnamed: 0           0
Hour                 0
Minutes              0
Sensor_alpha         0
Sensor_beta          0
Sensor_gamma         0
Sensor_alpha_plus    0
Sensor_beta_plus     0
Sensor_gamma_plus    0
Insect               0
dtype: int64

In [747]:
train.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
6996    False
6997    False
6998    False
6999    False
7000    False
Length: 7001, dtype: bool

In [748]:
train.duplicated().sum()

0

In [749]:
print(train.isnull().sum())
    

Unnamed: 0           0
Hour                 0
Minutes              0
Sensor_alpha         0
Sensor_beta          0
Sensor_gamma         0
Sensor_alpha_plus    0
Sensor_beta_plus     0
Sensor_gamma_plus    0
Insect               0
dtype: int64


### EDA

In [750]:
train

Unnamed: 0  Hour  Minutes  Sensor_alpha  Sensor_beta  Sensor_gamma  \
0              0    22       26    119.910995   242.838324   -316.819222   
1              1    10       16    -90.790536  -269.470767   -182.581844   
2              2    21       42    -20.028003  -147.070212     50.280872   
3              3    21       17    -21.258567     0.467070    -86.164153   
4              4    18       16    -58.154501   -13.051195   -156.501167   
...          ...   ...      ...           ...          ...           ...   
6996        6996    21        0      6.576106   301.050638    146.682819   
6997        6997    18       57     -6.169382  -317.652257   -161.644320   
6998        6998    22       47     -7.289684  -406.732525   -212.097250   
6999        6999    18       14    -92.317105  -191.555040     88.371271   
7000        7000    21       31    -72.083585   -11.434977    -52.961743   

      Sensor_alpha_plus  Sensor_beta_plus  Sensor_gamma_plus  Insect  
0            250.195048        -53.547777        -112.049983       2  
1             95.394941         37.291944          48.525180       0  
2            -90.750386        -50.476556          85.399009       1  
3            -21.813529       -209.256006          16.291882       0  
4             48.392938       -110.008860         -10.285138       2  
...                 ...               ...                ...     ...  
6996        -209.480741       -129.776336         -51.226256       1  
6997         248.055724       -112.626344          99.463913       0  
6998         248.745127        116.893077          32.806150       0  
6999          38.728565        -39.050466          20.356711       0  
7000         -72.696385        145.299227        -143.856243       1  

[7001 rows x 10 columns]

In [ ]:
plt.hist(train['Insect'])
plt.show()

In [ ]:
plt.hist(train['Hour'], bins=24)
plt.show()

In [ ]:
plt.hist(train['Minutes'], bins=24)
plt.show()

In [ ]:
plt.hist(train['Sensor_alpha'], bins=10)
plt.show()

In [ ]:
plt.hist(train['Sensor_beta'], bins=10)
plt.show()

In [ ]:
plt.hist(train['Sensor_gamma'], bins=10)
plt.show()

In [ ]:
plt.hist(train['Sensor_alpha_plus'], bins=10)
plt.show()

In [ ]:
plt.hist(train['Sensor_gamma_plus'], bins=10)
plt.show()

In [ ]:
train.columns

In [ ]:
import pandas_profiling
pandas_profiling.ProfileReport(train)

In [ ]:
train.nunique()

In [ ]:
sns.pairplot(train, hue='Insect')


In [ ]:
corelation = train.corr()

In [ ]:

sns.heatmap(corelation, xticklabels=corelation.columns, yticklabels=corelation.columns, annot=True)


In [ ]:
CorrMat = train.corr()
print(CorrMat)

### Despues del EDA decidimos quedarnos con las siguientes variables: Hour, Sensor_beta, Sensor_gamma, Sensor_alpha_plus. Principalmente por su mayor correlación entre estas y nuestra variable objetivo.  Aunque hemos visto que las clases estan distribuidas de forma desigual por lo que vamos a usar alguna técnica de sampling (Over Sampling) 

#### Procedemos a definir nuestras variables X & Y. En este caso nos quedamos con Hour, Sensor_beta, Sensor_gamma, Sensor_alpha_plus. 

In [753]:
X = train.iloc[:,  [1, 4, 5, 6]]
print('Primer modelo_x')
X.head()

Primer modelo_x


Hour  Sensor_beta  Sensor_gamma  Sensor_alpha_plus
0    22   242.838324   -316.819222         250.195048
1    10  -269.470767   -182.581844          95.394941
2    21  -147.070212     50.280872         -90.750386
3    21     0.467070    -86.164153         -21.813529
4    18   -13.051195   -156.501167          48.392938

#### La Variable a predecir, Insecto. 

In [754]:
Y = train['Insect']
Y.head()

0    2
1    0
2    1
3    0
4    2
Name: Insect, dtype: int64

In [755]:
test

Unnamed: 0  Hour  Minutes  Sensor_alpha  Sensor_beta  Sensor_gamma  \
1           7001    21        3   -193.619980    40.137081     85.419244   
2           7002    22       31     42.578382   -51.613402    125.055611   
3           7003    21       25    -64.150951   287.306752    -70.965473   
4           7004    18       11    193.750787   -61.989533   -110.347066   
5           7005    21        5    200.151155   -69.828082   -103.909275   
...          ...   ...      ...           ...          ...           ...   
2995        9995     3       26   -101.913083    87.337077     77.193476   
2996        9996    21        6     52.424913   -37.107249    120.373905   
2997        9997    21        0   -103.295133    34.736979   -195.018118   
2998        9998    20       13    170.027159   -73.100306   -117.330651   
2999        9999    19       17   -173.839238    66.386097   -141.968498   

      Sensor_alpha_plus  Sensor_beta_plus  Sensor_gamma_plus  
1            -26.266801       -125.391237          80.904973  
2            182.136746         -9.726951        -114.913402  
3             13.789738         38.187260         137.761691  
4            -16.864786        148.541916         232.424616  
5             58.307127          6.339606         -58.217237  
...                 ...               ...                ...  
2995         -79.694034         13.273965         143.004786  
2996         208.090551       -135.567057         -53.867634  
2997        -164.294768        -26.993064           6.063715  
2998          11.353824         -3.366007        -140.113661  
2999         197.558808        -44.847981         142.537872  

[2999 rows x 9 columns]

In [756]:
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.metrics import plot_confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, classification_report 

## MODEL 1

In [757]:
algosClass = []

In [758]:
algosClass.append(('Random Forest Classifier',RandomForestClassifier()))

In [759]:
print(algosClass)

[('Random Forest Classifier', RandomForestClassifier())]


In [760]:
results = []
names = []
for name, model in algosClass:
    print(name)
    print(model)
    result = cross_val_score(model, X,Y, cv=3, scoring='f1_macro')
    names.append(name)
    results.append(result)
    print(results)

Random Forest Classifier
RandomForestClassifier()
[array([0.85610743, 0.83981332, 0.85787058])]


In [761]:
for i in range(len(names)):
    print(names[i],results[i].mean())

Random Forest Classifier 0.851263775307259


In [762]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = .30, random_state = 123)

In [763]:
ALGO = RandomForestClassifier()
MODEL = ALGO.fit (X_train, Y_train)

In [764]:
Predictions = MODEL.predict(X_test)

In [765]:
Predictions

array([1, 0, 1, ..., 1, 1, 1])

In [766]:
CF_matrix = confusion_matrix(Y_test, Predictions,  labels=[0,1,2])

In [767]:
print(CF_matrix)

[[934  66  30]
 [ 49 805   6]
 [ 57  16 138]]


In [768]:
print(classification_report(Y_test, Predictions))

              precision    recall  f1-score   support

           0       0.90      0.91      0.90      1030
           1       0.91      0.94      0.92       860
           2       0.79      0.65      0.72       211

    accuracy                           0.89      2101
   macro avg       0.87      0.83      0.85      2101
weighted avg       0.89      0.89      0.89      2101



In [769]:
test

Unnamed: 0  Hour  Minutes  Sensor_alpha  Sensor_beta  Sensor_gamma  \
1           7001    21        3   -193.619980    40.137081     85.419244   
2           7002    22       31     42.578382   -51.613402    125.055611   
3           7003    21       25    -64.150951   287.306752    -70.965473   
4           7004    18       11    193.750787   -61.989533   -110.347066   
5           7005    21        5    200.151155   -69.828082   -103.909275   
...          ...   ...      ...           ...          ...           ...   
2995        9995     3       26   -101.913083    87.337077     77.193476   
2996        9996    21        6     52.424913   -37.107249    120.373905   
2997        9997    21        0   -103.295133    34.736979   -195.018118   
2998        9998    20       13    170.027159   -73.100306   -117.330651   
2999        9999    19       17   -173.839238    66.386097   -141.968498   

      Sensor_alpha_plus  Sensor_beta_plus  Sensor_gamma_plus  
1            -26.266801       -125.391237          80.904973  
2            182.136746         -9.726951        -114.913402  
3             13.789738         38.187260         137.761691  
4            -16.864786        148.541916         232.424616  
5             58.307127          6.339606         -58.217237  
...                 ...               ...                ...  
2995         -79.694034         13.273965         143.004786  
2996         208.090551       -135.567057         -53.867634  
2997        -164.294768        -26.993064           6.063715  
2998          11.353824         -3.366007        -140.113661  
2999         197.558808        -44.847981         142.537872  

[2999 rows x 9 columns]

## Sampling

In [770]:
from sklearn.metrics.pairwise import euclidean_distances
from collections import Counter 
from imblearn import under_sampling, over_sampling 
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler

In [771]:
import imblearn

In [772]:
print(sorted(Counter(train['Insect']).items()))

[(0, 3519), (1, 2793), (2, 689)]


DEF2 = train[train['Insect'] == 2]
DEF1 = train[train['Insect'] == 1]
DEF0 = train[train['Insect'] == 0]

In [773]:
print(DEF0.shape, DEF1.shape, DEF2.shape, train.shape)

(3519, 10) (2793, 10) (689, 10) (7001, 10)


In [774]:
x = train.iloc[:,  [1, 4, 5, 6]]
print('Model 2')
x.head()

Model 2


Hour  Sensor_beta  Sensor_gamma  Sensor_alpha_plus
0    22   242.838324   -316.819222         250.195048
1    10  -269.470767   -182.581844          95.394941
2    21  -147.070212     50.280872         -90.750386
3    21     0.467070    -86.164153         -21.813529
4    18   -13.051195   -156.501167          48.392938

In [775]:
y = train ['Insect']

In [776]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = .30, random_state = 123)

### Model 2 

In [777]:
from imblearn.over_sampling import RandomOverSampler
ROS = RandomOverSampler(random_state=0)
x_resampled, y_resampled = ROS.fit_resample(x_train, y_train)
print(sorted(Counter(y_resampled).items()), y_resampled.shape)

[(0, 2489), (1, 2489), (2, 2489)] (7467,)


In [778]:
algosClass = []
algosClass.append(('Random Forest Classifier',RandomForestClassifier()))
print(algosClass)

[('Random Forest Classifier', RandomForestClassifier())]


In [779]:
results = []
names = []
for name, model in algosClass:
    print(name)
    print(model)
    result = cross_val_score(model, x_resampled,y_resampled, cv=3, scoring='f1_macro')
    names.append(name)
    results.append(result)
    print(results)

Random Forest Classifier
RandomForestClassifier()
[array([0.94779915, 0.94278522, 0.94866813])]


In [780]:
for i in range(len(names)):
    print(names[i],results[i].mean())

Random Forest Classifier 0.9464174984141996


In [781]:
algo = RandomForestClassifier()
model = algo.fit (x_resampled, y_resampled)

In [782]:
Predi3 = model.predict(x_test)

In [783]:
Predi3

array([1, 0, 1, ..., 1, 1, 1])

In [784]:
from sklearn import metrics
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, roc_auc_score, roc_curve, f1_score

In [785]:
CON_MATRX = confusion_matrix(y_test, Predi3,  labels=[0,1,2])

In [786]:
print(CON_MATRX)

[[915  66  49]
 [ 50 803   7]
 [ 52  13 146]]


In [787]:
print(classification_report(y_test, Predi3))

              precision    recall  f1-score   support

           0       0.90      0.89      0.89      1030
           1       0.91      0.93      0.92       860
           2       0.72      0.69      0.71       211

    accuracy                           0.89      2101
   macro avg       0.84      0.84      0.84      2101
weighted avg       0.89      0.89      0.89      2101



In [788]:
print(classification_report(Y_test, Predictions))

              precision    recall  f1-score   support

           0       0.90      0.91      0.90      1030
           1       0.91      0.94      0.92       860
           2       0.79      0.65      0.72       211

    accuracy                           0.89      2101
   macro avg       0.87      0.83      0.85      2101
weighted avg       0.89      0.89      0.89      2101



In [789]:
test

Unnamed: 0  Hour  Minutes  Sensor_alpha  Sensor_beta  Sensor_gamma  \
1           7001    21        3   -193.619980    40.137081     85.419244   
2           7002    22       31     42.578382   -51.613402    125.055611   
3           7003    21       25    -64.150951   287.306752    -70.965473   
4           7004    18       11    193.750787   -61.989533   -110.347066   
5           7005    21        5    200.151155   -69.828082   -103.909275   
...          ...   ...      ...           ...          ...           ...   
2995        9995     3       26   -101.913083    87.337077     77.193476   
2996        9996    21        6     52.424913   -37.107249    120.373905   
2997        9997    21        0   -103.295133    34.736979   -195.018118   
2998        9998    20       13    170.027159   -73.100306   -117.330651   
2999        9999    19       17   -173.839238    66.386097   -141.968498   

      Sensor_alpha_plus  Sensor_beta_plus  Sensor_gamma_plus  
1            -26.266801       -125.391237          80.904973  
2            182.136746         -9.726951        -114.913402  
3             13.789738         38.187260         137.761691  
4            -16.864786        148.541916         232.424616  
5             58.307127          6.339606         -58.217237  
...                 ...               ...                ...  
2995         -79.694034         13.273965         143.004786  
2996         208.090551       -135.567057         -53.867634  
2997        -164.294768        -26.993064           6.063715  
2998          11.353824         -3.366007        -140.113661  
2999         197.558808        -44.847981         142.537872  

[2999 rows x 9 columns]

In [790]:
x

Hour  Sensor_beta  Sensor_gamma  Sensor_alpha_plus
0       22   242.838324   -316.819222         250.195048
1       10  -269.470767   -182.581844          95.394941
2       21  -147.070212     50.280872         -90.750386
3       21     0.467070    -86.164153         -21.813529
4       18   -13.051195   -156.501167          48.392938
...    ...          ...           ...                ...
6996    21   301.050638    146.682819        -209.480741
6997    18  -317.652257   -161.644320         248.055724
6998    22  -406.732525   -212.097250         248.745127
6999    18  -191.555040     88.371271          38.728565
7000    21   -11.434977    -52.961743         -72.696385

[7001 rows x 4 columns]

In [791]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2999 entries, 1 to 2999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Unnamed: 0         2999 non-null   int64  
 1   Hour               2999 non-null   int64  
 2   Minutes            2999 non-null   int64  
 3   Sensor_alpha       2999 non-null   float64
 4   Sensor_beta        2999 non-null   float64
 5   Sensor_gamma       2999 non-null   float64
 6   Sensor_alpha_plus  2999 non-null   float64
 7   Sensor_beta_plus   2999 non-null   float64
 8   Sensor_gamma_plus  2999 non-null   float64
dtypes: float64(6), int64(3)
memory usage: 234.3 KB


In [792]:
test.drop(test.iloc[:, [2,3,7,8]], inplace = True, axis = 1)

In [793]:
test

Unnamed: 0  Hour  Sensor_beta  Sensor_gamma  Sensor_alpha_plus
1           7001    21    40.137081     85.419244         -26.266801
2           7002    22   -51.613402    125.055611         182.136746
3           7003    21   287.306752    -70.965473          13.789738
4           7004    18   -61.989533   -110.347066         -16.864786
5           7005    21   -69.828082   -103.909275          58.307127
...          ...   ...          ...           ...                ...
2995        9995     3    87.337077     77.193476         -79.694034
2996        9996    21   -37.107249    120.373905         208.090551
2997        9997    21    34.736979   -195.018118        -164.294768
2998        9998    20   -73.100306   -117.330651          11.353824
2999        9999    19    66.386097   -141.968498         197.558808

[2999 rows x 5 columns]

In [794]:
test

Unnamed: 0  Hour  Sensor_beta  Sensor_gamma  Sensor_alpha_plus
1           7001    21    40.137081     85.419244         -26.266801
2           7002    22   -51.613402    125.055611         182.136746
3           7003    21   287.306752    -70.965473          13.789738
4           7004    18   -61.989533   -110.347066         -16.864786
5           7005    21   -69.828082   -103.909275          58.307127
...          ...   ...          ...           ...                ...
2995        9995     3    87.337077     77.193476         -79.694034
2996        9996    21   -37.107249    120.373905         208.090551
2997        9997    21    34.736979   -195.018118        -164.294768
2998        9998    20   -73.100306   -117.330651          11.353824
2999        9999    19    66.386097   -141.968498         197.558808

[2999 rows x 5 columns]

In [795]:
test.set_index('Unnamed: 0',inplace = True)

In [796]:
test

Hour  Sensor_beta  Sensor_gamma  Sensor_alpha_plus
Unnamed: 0                                                    
7001          21    40.137081     85.419244         -26.266801
7002          22   -51.613402    125.055611         182.136746
7003          21   287.306752    -70.965473          13.789738
7004          18   -61.989533   -110.347066         -16.864786
7005          21   -69.828082   -103.909275          58.307127
...          ...          ...           ...                ...
9995           3    87.337077     77.193476         -79.694034
9996          21   -37.107249    120.373905         208.090551
9997          21    34.736979   -195.018118        -164.294768
9998          20   -73.100306   -117.330651          11.353824
9999          19    66.386097   -141.968498         197.558808

[2999 rows x 4 columns]

### Test

####  Finalmente nos quedamos con el Modelo 2, aunque ambos son muy parecidos. 

In [797]:
Predi3 = model.predict(test)

In [798]:
Predi3

array([1, 0, 2, ..., 1, 0, 2])

In [799]:
Prediccion =pd.DataFrame({"Predicción": Predi3})

In [800]:
Prediccion

Predicción
0              1
1              0
2              2
3              0
4              1
...          ...
2994           2
2995           0
2996           1
2997           0
2998           2

[2999 rows x 1 columns]

In [801]:
test

Hour  Sensor_beta  Sensor_gamma  Sensor_alpha_plus
Unnamed: 0                                                    
7001          21    40.137081     85.419244         -26.266801
7002          22   -51.613402    125.055611         182.136746
7003          21   287.306752    -70.965473          13.789738
7004          18   -61.989533   -110.347066         -16.864786
7005          21   -69.828082   -103.909275          58.307127
...          ...          ...           ...                ...
9995           3    87.337077     77.193476         -79.694034
9996          21   -37.107249    120.373905         208.090551
9997          21    34.736979   -195.018118        -164.294768
9998          20   -73.100306   -117.330651          11.353824
9999          19    66.386097   -141.968498         197.558808

[2999 rows x 4 columns]

In [802]:
# test['Predicción']=Prediccion['Predicción']

In [803]:
test.dtypes

Hour                   int64
Sensor_beta          float64
Sensor_gamma         float64
Sensor_alpha_plus    float64
dtype: object

In [804]:
test.reset_index(drop=True, inplace=True)
Prediccion.reset_index(drop=True, inplace=True)

In [805]:
test

Hour  Sensor_beta  Sensor_gamma  Sensor_alpha_plus
0       21    40.137081     85.419244         -26.266801
1       22   -51.613402    125.055611         182.136746
2       21   287.306752    -70.965473          13.789738
3       18   -61.989533   -110.347066         -16.864786
4       21   -69.828082   -103.909275          58.307127
...    ...          ...           ...                ...
2994     3    87.337077     77.193476         -79.694034
2995    21   -37.107249    120.373905         208.090551
2996    21    34.736979   -195.018118        -164.294768
2997    20   -73.100306   -117.330651          11.353824
2998    19    66.386097   -141.968498         197.558808

[2999 rows x 4 columns]

In [806]:
Prediccion

Predicción
0              1
1              0
2              2
3              0
4              1
...          ...
2994           2
2995           0
2996           1
2997           0
2998           2

[2999 rows x 1 columns]

In [807]:
print(pd.concat([test, Prediccion], axis=1))

      Hour  Sensor_beta  Sensor_gamma  Sensor_alpha_plus  Predicción
0       21    40.137081     85.419244         -26.266801           1
1       22   -51.613402    125.055611         182.136746           0
2       21   287.306752    -70.965473          13.789738           2
3       18   -61.989533   -110.347066         -16.864786           0
4       21   -69.828082   -103.909275          58.307127           1
...    ...          ...           ...                ...         ...
2994     3    87.337077     77.193476         -79.694034           2
2995    21   -37.107249    120.373905         208.090551           0
2996    21    34.736979   -195.018118        -164.294768           1
2997    20   -73.100306   -117.330651          11.353824           0
2998    19    66.386097   -141.968498         197.558808           2

[2999 rows x 5 columns]


In [808]:
new = pd.concat([test, Prediccion], axis=1)

In [809]:
new

Hour  Sensor_beta  Sensor_gamma  Sensor_alpha_plus  Predicción
0       21    40.137081     85.419244         -26.266801           1
1       22   -51.613402    125.055611         182.136746           0
2       21   287.306752    -70.965473          13.789738           2
3       18   -61.989533   -110.347066         -16.864786           0
4       21   -69.828082   -103.909275          58.307127           1
...    ...          ...           ...                ...         ...
2994     3    87.337077     77.193476         -79.694034           2
2995    21   -37.107249    120.373905         208.090551           0
2996    21    34.736979   -195.018118        -164.294768           1
2997    20   -73.100306   -117.330651          11.353824           0
2998    19    66.386097   -141.968498         197.558808           2

[2999 rows x 5 columns]

In [810]:
lst = list(range(0, 1+2998))

In [811]:
print(lst)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

In [812]:
Prediccion =pd.DataFrame({"Predicción": Predi3})

In [813]:
New_index  =pd.DataFrame({"Index": lst})

In [814]:
New_index

Index
0         0
1         1
2         2
3         3
4         4
...     ...
2994   2994
2995   2995
2996   2996
2997   2997
2998   2998

[2999 rows x 1 columns]

In [815]:
new

Hour  Sensor_beta  Sensor_gamma  Sensor_alpha_plus  Predicción
0       21    40.137081     85.419244         -26.266801           1
1       22   -51.613402    125.055611         182.136746           0
2       21   287.306752    -70.965473          13.789738           2
3       18   -61.989533   -110.347066         -16.864786           0
4       21   -69.828082   -103.909275          58.307127           1
...    ...          ...           ...                ...         ...
2994     3    87.337077     77.193476         -79.694034           2
2995    21   -37.107249    120.373905         208.090551           0
2996    21    34.736979   -195.018118        -164.294768           1
2997    20   -73.100306   -117.330651          11.353824           0
2998    19    66.386097   -141.968498         197.558808           2

[2999 rows x 5 columns]

In [816]:
Test_nuwe = pd.concat([New_index, new], axis=1)

In [817]:
Test_nuwe

Index  Hour  Sensor_beta  Sensor_gamma  Sensor_alpha_plus  Predicción
0         0    21    40.137081     85.419244         -26.266801           1
1         1    22   -51.613402    125.055611         182.136746           0
2         2    21   287.306752    -70.965473          13.789738           2
3         3    18   -61.989533   -110.347066         -16.864786           0
4         4    21   -69.828082   -103.909275          58.307127           1
...     ...   ...          ...           ...                ...         ...
2994   2994     3    87.337077     77.193476         -79.694034           2
2995   2995    21   -37.107249    120.373905         208.090551           0
2996   2996    21    34.736979   -195.018118        -164.294768           1
2997   2997    20   -73.100306   -117.330651          11.353824           0
2998   2998    19    66.386097   -141.968498         197.558808           2

[2999 rows x 6 columns]

In [818]:
Test_nuwe.set_index('Index',inplace = True)

In [819]:
Test_nuwe

Hour  Sensor_beta  Sensor_gamma  Sensor_alpha_plus  Predicción
Index                                                                
0        21    40.137081     85.419244         -26.266801           1
1        22   -51.613402    125.055611         182.136746           0
2        21   287.306752    -70.965473          13.789738           2
3        18   -61.989533   -110.347066         -16.864786           0
4        21   -69.828082   -103.909275          58.307127           1
...     ...          ...           ...                ...         ...
2994      3    87.337077     77.193476         -79.694034           2
2995     21   -37.107249    120.373905         208.090551           0
2996     21    34.736979   -195.018118        -164.294768           1
2997     20   -73.100306   -117.330651          11.353824           0
2998     19    66.386097   -141.968498         197.558808           2

[2999 rows x 5 columns]

In [820]:
Test_nuwe.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2999 entries, 0 to 2998
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Hour               2999 non-null   int64  
 1   Sensor_beta        2999 non-null   float64
 2   Sensor_gamma       2999 non-null   float64
 3   Sensor_alpha_plus  2999 non-null   float64
 4   Predicción         2999 non-null   int64  
dtypes: float64(3), int64(2)
memory usage: 140.6 KB


In [821]:
Test_nuwe.drop(test.iloc[:, [0,1,2,3]], inplace = True, axis = 1)

In [822]:
Test_nuwe

Predicción
Index            
0               1
1               0
2               2
3               0
4               1
...           ...
2994            2
2995            0
2996            1
2997            0
2998            2

[2999 rows x 1 columns]

In [823]:
Test_nuwe.to_csv('/Users/mariojosetuppia/Desktop/Hackaton/results.csv')